# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Subcription_ID

stages:
  - stage: validation
    displayName: 'Terraform validation'
    jobs:
      - job: terraform
        displayName: 'Terraform Plan'
        steps: 
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        
        - script: terraform init

        - script: terraform plan
          env:
            TF_VAR_subscription_id: $(subscription_id)

        
        