name: Terraform Validation

on:
  push:
    branches:
      - development

jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./eviorment/development
        run: terraform init

      - name: Terraform Plan
        working-directory: ./eviorment/development
        env:
          TF_VAR_subscription_id: ${{ vars.SUBSCRIPTION_ID }}
        run: terraform plan